//~ Revision: 197, Copyright (C) 2014-2017: Willem Vree, contributions Stéphane David.
//~ This program is free software; you can redistribute it and/or modify it under the terms of the
//~ GNU General Public License as published by the Free Software Foundation; either version 2 of
//~ the License, or (at your option) any later version.
//~ This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//~ without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//~ See the GNU General Public License for more details. <http://www.gnu.org/licenses/gpl.html>.
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.owns=function(d,l){return Object.prototype.hasOwnProperty.call(d,l)};$jscomp.assign="function"==typeof Object.assign?Object.assign:function(d,l){for(var n=1;n<arguments.length;n++){var p=arguments[n];if(p)for(var r in p)$jscomp.owns(p,r)&&(d[r]=p[r])}return d};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,l,n){d!=Array.prototype&&d!=Object.prototype&&(d[l]=n.value)};$jscomp.getGlobal=function(d){d=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,d];for(var l=0;l<d.length;++l){var n=d[l];if(n&&n.Math==Math)return n}return globalThis};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(d,l,n,p){if(l){n=$jscomp.global;d=d.split(".");for(p=0;p<d.length-1;p++){var r=d[p];r in n||(n[r]={});n=n[r]}d=d[d.length-1];p=n[d];l=l(p);l!=p&&null!=l&&$jscomp.defineProperty(n,d,{configurable:!0,writable:!0,value:l})}};$jscomp.polyfill("Object.assign",function(d){return d||$jscomp.assign},"es6","es3");$jscomp.arrayIteratorImpl=function(d){var l=0;return function(){return l<d.length?{done:!1,value:d[l++]}:{done:!0}}};$jscomp.arrayIterator=function(d){return{next:$jscomp.arrayIteratorImpl(d)}};
$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(d,l){this.$jscomp$symbol$id_=d;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:l})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function d(n){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(n||"")+"_"+l++,n)}var l=0;return d}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.asyncIterator;d||(d=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};
$jscomp.iteratorFromArray=function(d,l){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var n=0,p={next:function(){if(n<d.length){var r=n++;return{value:l(r,d[r]),done:!1}}p.next=function(){return{done:!0,value:void 0}};return p.next()}};p[Symbol.iterator]=function(){return p};return p};$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6","es3");
$jscomp.findInternal=function(d,l,n){d instanceof String&&(d=String(d));for(var p=d.length,r=0;r<p;r++){var T=d[r];if(l.call(n,T,r,d))return{i:r,v:T}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(d,n){return $jscomp.findInternal(this,d,n).v}},"es6","es3");var VERSION=197,opt,onYouTubeIframeAPIReady,msc_credits,media_height,times_arr,offset_js,abc_arr,lpRec,media_file,abc_enc,play_list;
(function(){function d(){opt=Object.assign(opt,ca);$("#yubuse").prop("checked",!1);$("#yvdlbl, #vidyub").css("display","none");msc_credits=void 0;$("#credits").html("");media_height=void 0;$("#buttons").css("height","");da="";t=0;h=null}function l(a,b,c,f,e,d,g){this.xs=a;this.ymin=b;this.ymax=c;this.times=f;this.times.unshift(0);this.tixbts=g;this.line=0;this.msre=1;this.width=0;this.wijzer=$(document.createElementNS("http://www.w3.org/2000/svg","svg"));this.wijzer.attr("id","wijzer");this.wijzer.css("overflow",
"visible");this.shade=$(document.createElementNS("http://www.w3.org/2000/svg","rect"));this.shade.attr({width:"100%",height:"100%"});this.shade.attr("id","shade");this.wijzer.append(this.shade);this.tiktak=$(document.createElementNS("http://www.w3.org/2000/svg","text"));this.tiktak.attr("y",5);this.tiktak.css({fill:"green",stroke:"green","text-anchor":"end","font-size":"xx-large"});this.wijzer.append(this.tiktak);this.atag=$(document.createElementNS("http://www.w3.org/2000/svg","text"));this.atag.attr("id",
"atag");this.atag.text("<");this.atag.css({fill:"red",stroke:"red","text-anchor":"middle"});this.btag=$(document.createElementNS("http://www.w3.org/2000/svg","text"));this.btag.attr("id","btag");this.btag.text(">");this.btag.css({fill:"red",stroke:"red","text-anchor":"middle"});"undefined"==typeof lpRec&&(lpRec={loopBtn:1,loopStart:0,loopEnd:f[f.length-1]},$("#lopctl").prop("checked",!1),opt.lopctl=0);this.hmargin=100;this.vmargin=50;this.tmargin=0<=opt.top_margin?opt.top_margin:this.vmargin;this.lastSync=
0;this.setScale();this.cursorTime=0;this.time_ix=1;this.tixlb=e;this.lbtix=d;this.repcnt=1;this.tAbcLast=this.nseqCur=this.noCursor=0}function n(){this.paused=!0;this.currentTime=0;this.klok=-1;this.step=200;this.playing=0;la(.1,4,.05)}function p(a,b,c){var f=a!=v.scrollLeft,e=b!=v.scrollTop;if(f||e)ma?(v.style["scroll-behavior"]=c||f?"auto":"smooth",v.scroll(a,b)):(f&&(v.scrollLeft=a),e&&$(v).animate({scrollTop:b}))}function r(){var a=$("#abclbl"),b=a.html(),c=$("#impbox").prop("checked");a.toggleClass("abcimp",
c);a.html(c?b.replace("score file","<b>import</b>"):b.replace("<b>import</b>","score file"));c&&!opt.btns&&$("#btns").click()}function T(a,b){if(0>a.indexOf("//# This page"))alert("not a preload file");else{a=b.replace(/\n/g,"");b=a.match(/offset_js = (.*);/);1<b.length&&(q=offset_js=parseFloat(b[1]));b=a.match(/times_arr = (.*);abc_arr/);var c;1<b.length&&(c=na(JSON.parse(b[1])));k&&(k.times=c,k.times.unshift(0));$("#impbox").prop("checked",!1);r()}}function oa(a){var b=a.slice(0,4E3);if($("#impbox").prop("checked"))T(b,
a);else if(0<=b.indexOf("//# This page")||0<=b.indexOf("play_list")){d();eval(a);for(var c in ca)c in opt||(opt[c]=ca[c]);I()}else 0<=b.indexOf("X:")?pa(a):-1==b.indexOf("<?xml ")?alert("not an xml file nor an abc file"):(a=$.parseXML(a),a=vertaal(a,{p:"f",t:1,u:opt.repufld,v:3,mnum:0}),a[1]&&$("#err").append(a[1]+"\n"),pa(a[0]))}function Ga(a){$("#err").text("");lpRec=offset_js=times_arr=void 0;var b=a[0].link;C=a[0].name.split(".")[0];$("#wait").toggle(!0);$("#err").text("link: "+b+"\n");$.get(b,
"",null,"text").done(function(a,b){$("#err").append("preload: "+b+"\n");abc_arr=a.split("\n");I()}).fail(function(a,b,e){$("#wait").append("\npreload failed: "+b)})}function qa(a,b){$("#err").text("");offset_js=times_arr=void 0;$("#impbox").prop("checked")||(lpRec=void 0);var c=new FileReader;c.onload=function(a){oa(c.result)};if(a="dd"==a?b[0]:$("#fknp").prop("files")[0])C=a.name.split(".")[0],c.readAsText(a)}function Ha(a){a.stopPropagation();a.preventDefault();$("body").toggleClass("indrag",!1);
a=a.dataTransfer.files;/video|audio/.test(a[0].type)?ea("dd",a):qa("dd",a)}function ea(a,b){"dbx"==a?(a=b[0],b=a.link):(a="dd"==a?b[0]:$("#mknp").prop("files")[0],b=window.URL.createObjectURL(a));U(a.name,b)}function Ia(){$("#yubid")[0].checkValidity()?(opt.yubvid=$("#yubid").val(),U("","")):alert("The youtube video id should be 11 characters long,\neach from 'A' to 'Z', 'a' to 'z', '0' to '9', '-' or '_'")}function la(a,b,c){for(z=[];a<=b+.001;a+=c)a=Math.round(100*a)/100,z.push(a)}function ra(a){function b(a){$("#yubuse").attr("disabled",
a);$("#yublbl").css("color",a?"#aaa":"#000");$("#yubload").toggle(a)}a&&(sa=a);"undefined"==typeof YT?(b(!0),$("#yubuse").prop("checked",!1),$.getScript("https://www.youtube.com/iframe_api")):(b(!1),sa())}function U(a,b){b=b.replace("www.dropbox","dl.dropboxusercontent").split("?")[0];da=0==b.indexOf("http")?b:a;a=a.split("?")[0];$("#vid, #aud").attr("src","");V&&V.stopVideo();J.clearKlok();var c=0<=opt.btime?opt.btime:q;if(a){t=0;if(/\.webm$|\.mp4$/i.test(a)){a=$("#vid");if(0==a.length)return;$("#vidyub, #aud").css("display",
"none");a.css("display","inline-block");$("#buttons").toggleClass("video",!0)}else{a=$("#aud");if(0==a.length)return;$("#vidyub, #vid").css("display","none");a.css("display","inline-block");$("#buttons").toggleClass("video",!1)}h=a.get(0);/\.ogg$/i.test(b)&&(h.canPlayType("audio/ogg")||(b=b.replace(/\.ogg$/i,".mp3")));/\.webm$/i.test(b)&&(h.canPlayType("video/webm")||(b=b.replace(/\.webm$/i,".mp4")));a.attr("src",b);a.on("playing",function(){J.setKlok(W,100);h.playbackRate=opt.speed});a.on("pause",
function(){J.pause()});a.on("loadedmetadata",function(){A();h.currentTime=c});h.volume=.7;la(.5,2,.05);D(0);A()}else t=1,$("#vid, #aud").css("display","none"),$("#vidyub").css("display","inline-block"),$("#buttons").toggleClass("video",!0),ra(function(){h=V;z=h.getAvailablePlaybackRates();D(0);A();h.cueVideoById({videoId:opt.yubvid,startSeconds:c});h.setVolume(70)})}function ta(){var a=$("#yubuse").prop("checked");$("#medlbl").css("display",a?"none":"block");$("#yvdlbl").css("display",a?"block":"none")}
function fa(){var a=parseInt($("body").css("width"))/2,b=parseInt($("#vid").css("width"))/2,c=parseInt($("#vidyub").css("width"))/2,f=parseInt($("#aud").css("width"))/2;$("#vid").css("margin-left",opt.ctrmed?(a-b).toFixed()+"px":"0px");$("#vidyub").css("margin-left",opt.ctrmed?(a-c).toFixed()+"px":"0px");$("#aud").css("margin-left",opt.ctrmed?(a-f).toFixed()+"px":"0px");$("#meddiv").css("text-align",opt.ctrmed?"left":"center")}function A(){h&&$(h).toggle(!opt.noplyr);$("#buttons").toggleClass("noheight",
!!opt.noplyr);var a=$("#btns").prop("checked"),b=parseFloat($("#buttons").css("height")),c=parseFloat($("body").css("height"));a=a?parseFloat($("#err").css("height")):0;c=100-(100*(b+a)/c).toFixed();$("#notation").css("height",c+"%");$("#vidyub").css("width",(1.52*b).toFixed());fa();L()}function pa(a){function b(a){a=Object.keys(a).map(function(a){return parseFloat(a)});a.sort(function(a,b){return a-b});return a}function c(a){var b={diamond:1,triangle:1,square:1,normal:1},c=I,f,e="default",d={"default":[]},
M={"default":[]};a=a.split("\n");for(f=0;f<a.length;++f){var g=a[f];if(0<=g.indexOf("I:percmap")){g=g.split(" ").map(function(a){return a.trim()});var u=g[4];u in b&&(u=u+"+,"+u);g="%%map perc"+e+" "+g[1]+" print="+g[2]+" midi="+g[3]+" heads="+u;d[e].push(g)}0<=g.indexOf("%%MIDI")&&M[e].push(g);0<=g.indexOf("V:")&&(u=g.match(/V:\s*(\S+)/))&&(e=u[1],e in d||(d[e]=[],M[e]=[]))}b=Object.keys(d).sort();for(f=0;f<b.length;++f)c=c.concat(d[b[f]]);e="default";for(f=0;f<a.length;++f)g=a[f],0<=g.indexOf("I:percmap")||
0<=g.indexOf("%%MIDI")||(0<=g.indexOf("V:")||0<=g.indexOf("K:")?((u=g.match(/V:\s*(\S+)/))&&(e=u[1]),c.push(g),e in M&&M[e].length&&(c=c.concat(M[e]),delete M[e]),0<=g.indexOf("perc")&&-1==g.indexOf("map=")&&(g+=" map=perc"),0<=g.indexOf("map=perc")&&0<d[e].length&&c.push("%%voicemap perc"+e),0<=g.indexOf("map=off")&&c.push("%%voicemap")):c.push(g));return c.join("\n")}var f="",e="",d={},g={},n=[],m,p=[],ha=[],r=[],t=[],v=[],F=[],w=[],N=[[0,0,1]],O=[],x=0,z=[0],A=[],C={},D=[],I='%%beginsvg\n<defs>,<text id="x" x="-3" y="0">&#xe263;</text>,<text id="x-" x="-3" y="0">&#xe263;</text>,<text id="x+" x="-3" y="0">&#xe263;</text>,<text id="normal" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal-" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal+" x="-3.7" y="0">&#xe0a4;</text>,<g id="circle-x"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<g id="circle-x-"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<path id="triangle" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle-" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle+" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="fill:#000"></path>,<path id="square" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square-" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square+" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="fill:#000"></path>,<path id="diamond" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond-" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond+" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="fill:#000"></path>,</defs>\n%%endsvg'.split(",");
X="";y=[];P=[];k=null;q=0;R=.1;Y=0;var G=$("#notation");$("body").attr("title","");G.empty();G.append('<div style="height:500px">&nbsp;</div>');var K=function(a){var b;a=a.replace(/\r\n/g,"\n");a=a.split(/^\s*X:/m);if(1==a.length)return[];var c=a[1].split(/^\s*$/m);c=a[0]+"X:"+c[0];a=c.split(/\r\n|[\n\r\u0085\u2028\u2029]/);for(c=0;c<Math.min(100,a.length);++c)(b=a[c].match(/%%scale\s*([\d.]+)/))&&1==b[1]&&(a[c]="%%scale 0.99");return a}(a);a=K.join("\n");0<=a.indexOf("percmap")&&(a=c(a));var E=new Abc({img_out:function(a){-1!=
a.indexOf("<svg")&&(a=a.replace(/width="(\d*)px"\s*height="(\d*)px"/,'width="$1px" height="$2px" viewbox="0 0 $1 $2"'),d=b(d),g=b(g),1<d.length&&d[1]<Math.min.apply(null,ha)&&d.splice(0,1),d=d.filter(function(a,b,c){return 0==b||15<a-c[b-1]}),n.push({xs:d,ys:g}),d={},g={},ha=[],x+=1);f+=a},errmsg:function(a,b,c){e+=a+"\n"},read_file:function(a){return""},anno_start:function(a,b,c,f,e,u,h){if("note"==a||"rest"==a)ha.push(E.ax(f)),f=Math.round(100*E.ax(f))/100,e=Math.round(100*E.ay(e))/100,h=E.ah(h),
C[b]=[x,f,e,u,h];"bar"==a&&(f=E.ax(f),e=E.ay(e),h=E.ah(h),d[f]=1,g[e]=1,g[e+h]=1,m=E.ax(0),d[m]=1)},get_abcmodel:function(a,b,c){var f=768;c=0;var e=0;try{var d=b[0].meter.a_meter[0].top}catch(Ua){d="4"}for(;a;a=a.ts_next){switch(a.type){case 8:case 10:A.push({time:a.time,iabc:a.istart,vce:a.v,inv:a.invis})}if(0==a.v)switch(a.type){case 14:f=a.tempo_notes.reduce(function(a,b){return a+b});f=f*a.tempo/60;break;case 8:case 10:c+=a.dur/f;break;case 0:"soln"in a&&(e=a.time);if(a.time==e){F[F.length-1]+=
a.bar_type;break}w.push(c);c=0;d=d.replace("C|","2").replace("C","4");v.push(parseInt(d));F.push(a.bar_type);r.push(a.text);z.push(a.time);break;case 6:d=a.a_meter.length?a.a_meter[0].top:"4"}}Z.forEach(function(a){var b=a.parentNode;b&&b.removeChild(a)});S=[];d="#f9f #3cf #c99 #f66 #fc0 #cc0 #ccc".split(" ");b=b.length;for(c=0;c<b;++c)e=1<<c&0?"0":"",a=document.createElementNS("http://www.w3.org/2000/svg","rect"),a.setAttribute("fill",d[c%d.length]+e),a.setAttribute("fill-opacity","0.5"),a.setAttribute("width",
"0"),Z.push(a),S.push(-1)}});E.tosvg("abc2svg",a);""!=e&&$("#err").append(e);G.append(f);G.append('<div style="height:500px">&nbsp;</div>');y=G.find("svg");y.each(function(){var a=$(this).find(".g");P.push(a.length?a:$(this))});a=[];G=[];for(var H=[],Q=0;Q<n.length;++Q){var B=n[Q];a[Q]=B.xs;G[Q]=B.ys[0];H[Q]=B.ys[B.ys.length-1]}(function(){for(var a=0,b=1,c=n[a].xs.length,f=0,e=0,d=1,g=0,u=1,h=1,k=0,l={};;){var m=r[f-1];if(m=m?m.match(/[,\d]*(\d)/):null)m=parseInt(m[1]),m!=k&&(k=m);if(!k||k>=u)D.push(f),
e+=w[f],p.push(e),t.push(v[f]),O[a]||(O[a]=[]),O[a][b]||(O[a][b]=[]),O[a][b][h]=N.length,N.push([a,b,h]);"|"!=F[f]&&(k=0);m=/^:/.test(F[f]);if(!m||1!=u||l[f]||opt.repskip){if(m&&(u=1),/:$/.test(F[f])&&(d=N.length,g=f+1,u=1),f+=1,b+=1,b>=c){b=1;a+=1;if(a>=n.length)break;c=n[a].xs.length}}else u=2,h+=1,l[f]=1,f=g,b=N[d][1],a=N[d][0],c=n[a].xs.length}})();"undefined"!=typeof times_arr&&(p=na(times_arr));"undefined"!=typeof offset_js&&(q=offset_js);opt.offset&&(q=opt.offset);X=K;k=new l(a,G,H,p,N,O,t);
y.each(function(){$(this).mousedown(Ja)});h||(h=J);setTimeout(function(){ua();L()},0);K=A.map(function(a){return{t:a.time,vce:a.vce,xy:C[a.iabc]}});a=K[K.length-1];a.t+=1;K.push(a);k.ntsSeq=K;k.barTimes=z;k.tix2mix=D}function Ka(a){var b,c;var f=Z[a.vce];if(b=a.xy){var e=b[0];var d=b[1];var g=b[2];var h=b[3];b=b[4];a.inv&&(b=h=0);e!=S[a.vce]&&((c=f.parentNode)&&c.removeChild(f),c=P[e][0],c.insertBefore(f,c.firstChild),S[a.vce]=e);f.setAttribute("x",d);f.setAttribute("y",g);f.setAttribute("width",
h);f.setAttribute("height",b)}else f.setAttribute("width",0),f.setAttribute("height",0)}function na(a){a=a.map(function(a){return a.slice(1)});return a=a.reduce(function(a,c){return a.concat(c)})}function W(){if(h){var a=(t?h.getCurrentTime():h.currentTime)-q,b=a;0>a&&(a=0);opt.lopctl&&(a>lpRec.loopEnd&&(a=lpRec.loopStart),a<lpRec.loopStart&&(a=lpRec.loopStart+.01),a!=b&&(t?h.seekTo(a+q,!0):h.currentTime=a+q));k&&k.time2x(a,0,0)}}function Ja(a){a.preventDefault();a.stopPropagation();var b=y.get().indexOf(this);
a=a.clientX;var c=this.getBoundingClientRect();a-=c.left+10;k.x2time(a,b)}function va(){$("#sync_out").css("display",opt.synbox?"block":"none");k&&opt.synbox&&k.showSyncInfo()}function wa(){$("#medbts").css("display",opt.btns?"inline":"none");$("#err").css("display",opt.btns?"block":"none");A();opt.btns&&"undefined"==typeof FileReader&&$("#notation").prepend("<h3>Your browser does not support reading of local files ...</h3>but you can use the preload feature.")}function ia(){k&&(k.nseqCur=0,L());
$("#notation svg").css("margin-left",opt.ctrnot?"auto":"0px");$("#notation svg").css("margin-right",opt.ctrnot?"auto":"0px")}function xa(){var a=$("#spdctl").prop("checked");$("#spdlbl").css("display",a?"block":"none")}function ya(){function a(a){$("#drpuse").prop("checked",!a);$("#drpuse").attr("disabled",a);$("#drplbl").css("color",a?"#aaa":"#000")}if("undefined"==typeof Dropbox)a(!0),$.ajax({url:"https://www.dropbox.com/static/api/2/dropins.js",dataType:"script",cache:!0}).done(function(){a(!1);
Dropbox.init({appKey:"ckknarypgq10318"});La();ya()});else{var b=$("#drpuse").prop("checked");$(".dropbox-dropin-btn").css("display",b?"inline-block":"none");$("#fknp, #mknp").css("display",b?"none":"inline-block")}}function Ma(a,b){function c(){e<=f&&(x=setTimeout(c,d),k.tiktak.text(e),e+=1)}clearInterval(x);x=0;var f=k.tixbts[a-1];var e=1;var d=(k.times[a]-b)/f/opt.speed*1E3;x=setTimeout(c,0)}function za(){k&&setTimeout(function(){clearInterval(x);x=0;k.tiktak.text("")},0)}function Na(a,b){function c(){$("#countin").toggle(!1);
clearInterval(x);x=0}function f(){$("#countin").html("<b>"+e.num+"</b>").toggle(!0);0==e.num--&&(c(),aa(a,b))}if(x)c();else{a=a.replace(":true",":false");var e=k.compCountIn();f();x=setInterval(f,1E3*e.time)}}function aa(a,b){if(h){var c=a.split(":"),f="true"==c[0],e=parseFloat(c[1]);c="true"==c[2];var d=t?h.getPlayerState():0,g=t?1!=d:h.paused;t?5!=d&&h.seekTo(e,!0):h.currentTime=e;if(g&&f||!g&&!f){if(c){Na(a,b);return}if(b){setTimeout(function(){aa(a,0)},b);return}t?h.playVideo():h.play();opt.metro&&
k&&(k.time_ix=0)}else t?5!=d&&h.pauseVideo():h.pause(),opt.metro&&za();b=!opt.lncsr&&!f;k&&k.time2x(e-q,b,0)}}function ja(a,b){a=a+":"+b.toFixed(2)+":"+(a&&$("#cntin").prop("checked"));w?w.send(a):aa(a,0)}function H(a){var b=a.key,c=1;switch(b){case "ArrowLeft":case "Left":k.goMsre(0);break;case "ArrowRight":case "Right":k.goMsre(1);break;case "Spacebar":case " ":a.preventDefault&&a.preventDefault();if(!h)break;ja(!0,t?h.getCurrentTime():h.currentTime);break;case "a":$("#autscl").click();break;case "f":$("#btns").click();
break;case "h":$("#help").toggleClass("showhlp");break;case "l":$("#lncsr").click();break;case "m":$("#menu label").toggle();break;case "s":opt.spdctl&&!opt.lopctl?$("#lopctl").click():opt.lopctl&&!opt.spdctl?$("#spdctl").click():$("#spdctl, #lopctl").click();break;case "+":D(1);break;case "-":D(-1);break;default:c=0}if(opt.synbox&&k&&!c){switch(b){case ",":a.ctrlKey?q+=R:k.changeTimesKeyb(R);break;case ".":a.ctrlKey?q-=R:k.changeTimesKeyb(-R);break;case "w":Aa()}a.preventDefault();k.showSyncInfo()}}
function ka(){fa();if(k){if(y[0].width.baseVal.value>screen.width||opt.autscl)k.setSize.call(k),k.setScale.call(k);L(!0)}}function Oa(a){a=a.map(function(a){return window.btoa(unescape(encodeURIComponent(a)))}).join("++");for(var b=[],c=0;c<=a.length;)b.push(a.substr(c,150)),c+=150;return b}function Pa(a){function b(b){return a.join("").split(b).map(function(a){return decodeURIComponent(escape(window.atob(a)))})}try{var c=b("++")}catch(f){c=b("+")}return c.join("\n")}function Aa(){var a,b=[],c="[";
var f='media_file = "'+(t?"":da)+'";\n';var e="undefined"!=typeof msc_credits?"msc_credits = "+JSON.stringify(msc_credits)+";\n":"";var d="offset_js = "+q.toFixed(2)+";\n";opt.synbox=0;var g="opt = "+JSON.stringify(opt)+";\n";opt.synbox=1;var h=lpRec.loopBtn?"lpRec = "+JSON.stringify(lpRec)+";\n":"";for(a=k.times.map(function(a){return a.toFixed(2)});a.length;){var l=a[9];b.push(c+a.splice(0,10).join(",")+"]");c="["+l+","}a="times_arr = ["+b.join(",\n")+"];\n";$("#encr").prop("checked")?(c=Oa(X).map(function(a){return JSON.stringify(a)}),
b=['"X:1"']):(c=[""],b=X.map(function(a){return JSON.stringify(a)}));c="abc_enc = ["+c.join(",\n")+"];\n";b="abc_arr = ["+b.join(",\n")+"];\n";a='//########################################\n//# This page contains score data, timing data and the media file path. Save it as a text file in\n//# the same folder as abcweb.html. Abcweb preloads score and media when it is opened with the\n//# file name as parameter in the url, for example: http://your.domain.org/abcweb.html?file_name\n//# Also works locally with file:///path/to/abcweb.html?file_name\n//# **** You have to correct the path to the media file below! (media_file="...";) ****\n//########################################\n//#\n'+
(f+e+d+g+h+a+b+c);var n="data:text/plain;charset=utf-8;base64,"+btoa(unescape(encodeURIComponent(a)));if($("#drpuse").prop("checked"))$("#err").text(""),Dropbox.save(n,C+".js",{success:function(){$("#err").text('"'+C+'.js" saved to your Dropbox.\n')},progress:function(a){},cancel:function(){},error:function(a){$("#err").text("Error: "+a+"\n");$("#err").append("fnm: "+C+", len: "+n.length+"\n")}});else try{var m=document.createElement("a");m.href=n;m.download=C+".js";m.text="Save synchronization data";
$("#saveDiv").append(m);m.click()}catch(Va){confirm("Do you want to save your synchronization data?")&&(document.open("text/html"),document.write("<pre>"+a+"</pre>"),document.close())}}function Ba(a){d();$("#err").text("");var b="",c="",f,e,h="";var g=window.location.href.replace("?dl=0","").split("?");a&&(g=["",a]);if(a=g[0].match(/:\/\/([^/:]+)/))var k=a[1];if(1<g.length){var l=g[1].split("&");for(e=0;e<l.length;e++)g=l[e].replace(/d:(\w{15}\/[^.]+\.)/,"https://dl.dropboxusercontent.com/s/$1"),
(a=g.match(/xml=(.*)/))?b=decodeURIComponent(a[1]).replace("www.dropbox","dl.dropboxusercontent"):(a=g.match(/med=(.*)/))?h=a[1]:(a=g.match(/tmr=(\d*)/))?m.top_margin=parseInt(a[1]):(a=g.match(/mht=(\d*)/))?m.media_height=parseInt(a[1]):(a=g.match(/tb=([\d.]*)/))?m.btime=parseFloat(a[1]):(a=g.match(/te=([\d.]*)/))?m.etime=parseFloat(a[1]):(a=g.match(/off=([+-]?[\d.]+)/))?m.offset=parseFloat(a[1]):(a=g.match(/ip=(\d+.\d+.\d+.\d+)/))?m.ipadr=a[1]:(a=g.match(/^d([\d.]+)$/))?m.delay=parseFloat(a[1]):
g.match(/ip=host/)&&k?m.ipadr=k:"mstr"==g?m.mstr=1:"jmp"==g?m.jump=1:"syn"==g?m.synbox=1:"nb"==g?m.no_menu=1:"sp"==g?m.spdctl=m.lopctl=1:"ur"==g?m.repufld=1:"npl"==g?m.noplyr=1:"ncr"==g?m.nocsr=1:"asc"==g?m.autscl=1:"cm"==g?m.ctrmed=1:"cs"==g?m.ctrnot=1:"nomed"==g?(m.nomed=1,m.noplyr=1):c=g,/(\.xml$)|(\.abc$)/.test(c)&&(b=c,c=""),/(\.mp3$)|(\.mp4$)|(\.ogg$)|(\.webm$)/.test(c)&&(h=c,c="");h&&(11==h.length&&-1==h.indexOf(".")?opt.yubvid=h:media_file=decodeURIComponent(h).replace("www.dropbox","dl.dropboxusercontent"));
(c||b)&&$("#wait").toggle(!0);b?$.get(b,"",null,"text").done(function(a,b){$("#err").append("preload: "+b+"\n");abc_arr=a.split("\n");I()}).fail(function(a,b,c){$("#wait").append("\npreload failed: "+b)}):c&&(0<=c.indexOf("dropbox.com")&&(c+="?dl=1"),$.getScript(c).done(function(a,b){$("#err").append("preload: "+b+"\n");I()}).fail(function(a,b,e){$("#wait,#err").append("preload failed: "+e+", trying script tag ...\n");f=document.createElement("script");f.src=c;f.onload=function(){I()};f.onerror=function(){$("#wait").append("\npreload failed")};
document.head.appendChild(f);document.head.removeChild(f)}))}return c||b}function I(){if(0==B&&play_list)$("body").trigger("play_end");else{if("undefined"!=typeof abc_arr){var a=abc_arr.join("\n");"undefined"!=typeof abc_enc&&abc_enc.length&&(a=Pa(abc_enc),opt.no_menu=1);oa(a)}for(var b in m)opt[b]=m[b];"nospd"in opt&&(opt.spdctl=!opt.nospd,opt.nospd=void 0);"undefined"!=typeof media_file&&media_file&&!opt.nomed&&(U(media_file,media_file),opt.btns=0);opt.yubvid&&!opt.nomed&&(U("",""),opt.btns=0);
"undefined"!=typeof msc_credits&&(a=msc_credits.reduce(function(a,b){return a+b}),$("#credits").html(a));"undefined"!=typeof media_height&&(opt.media_height=media_height);opt.no_menu&&($("#sync").css("display","none"),opt.btns=0,$("body").off("dragenter dragleave drop dragover"),$("body").on("contextmenu",function(a){a.preventDefault()}),h.controlsList&&h.controlsList.add("nodownload"));$("#wait").toggle(!1);Ca(!1)}}function Ca(a){var b;if(a)for(b in m)opt[b]=m[b];opt.ipadr&&Qa(opt.ipadr);opt.media_height&&
$("#buttons").css("height",opt.media_height);opt.offrol&&$("#rollijn").css("top",opt.offrol);opt.offset&&(q=opt.offset);for(b in opt)$("#"+b).prop("checked",opt[b]);wa();ia();xa();va();ka();$("#sync, #medbts, #meddiv, #err").css("visibility","visible");$("#rollijn").css("display",opt.dotted?"block":"none");B&&H({key:" "})}function ba(a){$("#err").append(a+"\n")}function Qa(a){w?ba("websocket already open"):(w=new WebSocket("ws://"+a+":8091/"),w.onmessage=function(a){"master"==a.data?$("#mbar").css("background",
"rgba(255,0,0,0.2)"):aa(a.data,100*opt.delay)},w.onerror=function(a){ba("socket error (server inaccessible?)");w=null},w.onopen=function(a){$("#mbar").css("background","rgba(0,255,0,0.2)");opt.mstr&&w.send("master");ba("connection opened")},w.onclose=function(a){$("#mbar").css("background","");ba("connection closed: "+a.code);w=null})}function Ra(a){if(!Da()&&("meddiv"==a.target.id||"credits"==a.target.id)){a.preventDefault();a.stopPropagation();$("#buttons").css("opacity","0.5");$("#streep").css("opacity",
"1.0");var b="touchstart"==a.type,c=$("#meddiv"),f=b?a.originalEvent.touches[0].clientY:a.pageY,e=$("#buttons").height();c.css("cursor","row-resize");c.on("mousemove touchmove",function(a){var c=$("body").height();opt.media_height=(100*(e+(b?a.originalEvent.touches[0].clientY:a.pageY)-f)/c).toFixed()+"%";$("#buttons").css("height",opt.media_height)});c.on("mouseup touchend",function(a){$("#buttons").css("opacity","1.0");$("#streep").css("opacity","0.0");c.off("mousemove touchmove mouseup touchend");
c.css("cursor","initial");A()})}}function Sa(a){a.preventDefault();var b="touchstart"==a.type;$("#rollijn").toggleClass("rolgroen");var c=b?$("#rollijn"):$("body");c.on(b?"touchmove":"mousemove",function(a){$("#notation").offset();opt.offrol=(100*((b?a.originalEvent.touches[0].clientY:a.clientY)-15)/document.body.clientHeight).toFixed(2)+"%";$("#rollijn").css("top",opt.offrol);L(!0)});c.on(b?"touchend":"mouseup",function(a){c.off("mousemove touchmove mouseup touchend");$("#rollijn").toggleClass("rolgroen")})}
function D(a){if(2==a){a=$("#speed").val();var b=a-opt.speed;.06>=Math.abs(b)?a=0<b?1:-1:(opt.speed=a,a=0)}b=z.map(function(a,b){return{x:Math.abs(a-opt.speed),i:b}}).sort(function(a,b){return a.x-b.x})[0].i;-1==a&&0<b&&(opt.speed=z[b+a]);1==a&&b<z.length-1&&(opt.speed=z[b+a]);0==a&&(opt.speed=z[b]);$("#speed").val(opt.speed.toFixed(2));h&&!t&&(h.playbackRate=opt.speed);h&&t&&h.setPlaybackRate(opt.speed)}function ua(){k&&k.drawTags();opt.lopctl=$("#lopctl").prop("checked");$("#atag").css("display",
opt.lopctl?"block":"none");$("#btag").css("display",opt.lopctl?"block":"none")}function La(){var a=Dropbox.createChooseButton({success:Ga,cancel:function(){},linkType:"direct",multiselect:!1,extensions:[".xml",".abc",".txt",".js"]}),b=Dropbox.createChooseButton({success:function(a){ea("dbx",a)},cancel:function(){},linkType:"preview",multiselect:!1,extensions:[".ogg",".mp3",".webm",".mp4"]});$("#abcfile").append(a);$("#mediafile").append(b)}function Ea(a){a=$(this).prop("checked");var b=$(this).attr("id");
opt[b]=a;switch(b){case "ctrnot":ia();break;case "ctrmed":fa();break;case "spdctl":xa();break;case "autscl":ka();break;case "lncsr":ia();break;case "btns":wa();break;case "synbox":va();break;case "noplyr":A();break;case "nocsr":k&&!J.paused&&(k.noCursor=a);break;case "metro":a||za();break;case "dotted":L()}}function Fa(){$("#menu label").css("display","none")}function Da(){var a="none"!=$("#menu label").css("display")||$("#help").hasClass("showhlp");a&&($("#help").toggleClass("showhlp",!1),setTimeout(Fa,
0));return a}function Ta(){var a=document.body,b=a.requestFullscreen||a.mozRequestFullScreen||a.webkitRequestFullscreen,c=document.exitFullscreen||document.mozCancelFullScreen||document.webkitExitFullscreen;b&&c&&($("#fscr").prop("checked")?b.call(a):c.call(document))}function L(a){$("#rollijn").css("display",opt.dotted?"block":"none");k&&(S.forEach(function(a,c,f){f[c]=-1}),k.line=-1,k.time2x(k.cursorTime,0,a))}var y,P,k,q,da,X,h,C,V,t=0,z=[],Y=0,sa,m={},w=null,R,J=new n,v,ma=0;opt={};var ca={jump:0,
no_menu:0,repufld:0,noplyr:0,nocsr:0,media_height:"",btns:1,ipadr:"",mstr:0,autscl:0,ctrmed:0,ctrnot:0,lncsr:0,opacity:.2,synbox:0,speed:1,top_margin:0,yubvid:"",nomed:0,delay:0,repskip:0,spdctl:0,lopctl:0,metro:0,btime:-1,etime:0,offrol:0,dotted:0};onYouTubeIframeAPIReady=function(){V=new YT.Player("vidyub",{events:{onReady:function(){$("#yubuse").prop("checked",!0);ta();ra()},onStateChange:function(a){a.data==YT.PlayerState.PLAYING?(J.setKlok(W,100),D(0)):J.pause();a.data==YT.PlayerState.CUED&&
A()}}})};var Z=[],S=[],B=0;l.prototype.setline=function(a){$("#wijzer").remove();this.sety(this.ymin[a],this.ymax[a]);this.line=a;this.wijzer.prependTo(P[a]);this.width=y[a].width.baseVal.value;var b=v.scrollTop;if(opt.dotted){a=$("#shade")[0].getBoundingClientRect().top;var c=$("#rollijn")[0].getBoundingClientRect().top+30;b=b+a-c}else if(this.line_offsets[a+1]>b+v.clientHeight-this.vmargin||this.line_offsets[a]<b+this.vmargin)b=this.line_offsets[a]-this.tmargin;return b};l.prototype.sety=function(a,
b){this.wijzer.attr("y",a.toFixed(2));this.wijzer.attr("width","2");this.wijzer.attr("height",(b-a).toFixed(2));this.shade.attr("fill","blue")};l.prototype.setx=function(a,b,c){var f=v.scrollLeft,e=f+v.clientWidth-this.hmargin;if(opt.lncsr){if(this.wijzer.attr("width","0"),a/=this.scale,a>e||a<f+this.hmargin)f=a>this.hmargin?a-this.hmargin:0}else if(this.wijzer.attr("x",b.toFixed(2)),this.wijzer.attr("width",(c-b).toFixed(2)),this.shade.attr("fill-opacity",this.noCursor?"0.0":""+opt.opacity),b/=this.scale,
c/=this.scale,c>e||b<f+this.hmargin)f=b>this.hmargin?b-this.hmargin:0;return v.scrollWidth>v.clientWidth?f:0};l.prototype.time2x=function(a,b,c){if(!Y){this.cursorTime=a;var f,e;var d=this.times;for(e=this.time_ix;e<d.length&&a>d[e];)e+=1;if(opt.etime&&a+q>opt.etime||!opt.etime&&e==d.length)t?1==h.getPlayerState()&&h.pauseVideo():h.paused||h.pause(),$("body").trigger("play_end");else{for(;0<e&&a<d[e-1];)--e;b&&.3>d[e]-a&&(d[e]=a-.01,console.log("tijdcor: "+(a-.01)+", maat: "+e),e<d.length-1&&(e+=
1));opt.metro&&e!=this.time_ix&&Ma(e,a);this.time_ix=e;this.repcnt=this.tixlb[e][2];this.msre=f=this.tixlb[e][1];var g=this.tixlb[e][0];b=this.line!=g?this.setline(g):v.scrollTop;var k=this.xs[g];g=d[e-1];var l=d[e];d=k[f-1]+10;k=k[f]+10;f=(a-g)/(l-g);g=d+(k-d)*f;l=this.times[this.times.length-1];a=0>=a||a>l?this.setx(0,0,0):this.setx(g,d,k);p(a,b,c);opt.synbox&&this.showSyncInfo();if(opt.lncsr){c=this.tix2mix[e-1];e=this.barTimes[c];e+=(this.barTimes[c+1]-e)*f;e<this.tAbcLast&&(this.nseqCur=0);for(c=
this.nseqCur;c<this.ntsSeq.length;++c)if(a=this.ntsSeq[c],!(a.t<e&&c<this.ntsSeq.length-1)){for(a=this.nseqCur;a<c;++a)Ka(this.ntsSeq[a]);this.nseqCur=c;break}this.tAbcLast=e}else Z.forEach(function(a){var b=a.parentNode;b&&b.removeChild(a)})}}};l.prototype.drawTags=function(){for(var a in{atag:1,btag:1})if(a in lpRec){var b=lpRec[a];this[a].prependTo(P[b.line]);this[a].attr("x",b.x);this[a].attr("y",this.ymin[b.line])}};l.prototype.doLoopTag=function(a,b,c,d,e){function f(a,b,c,d,f,e,h,k){if(!opt.lncsr){var l=
g.xs[c];e=g.times;b=l[h-1];l=l[h];h=e[k-1];k=e[k];lpRec.loopStart==h+.01&&(a="btag",f="loopEnd");lpRec.loopEnd==k-.01&&(a="atag",f="loopStart");"loopStart"==f?e=h+.01:(b=l,e=k-.01)}lpRec[a]={x:b.toFixed(2),line:c};lpRec.loopBtn=d;lpRec[f]=e;g.drawTags()}var g=this;switch(lpRec.loopBtn){case 1:f("atag",a,b,2,"loopStart",c,d,e);break;case 2:c>lpRec.loopStart&&f("btag",a,b,3,"loopEnd",c,d,e);break;case 3:var h=Math.abs(lpRec.loopStart-c);var k=Math.abs(lpRec.loopEnd-c);h<k?f("atag",a,b,3,"loopStart",
c,d,e):f("btag",a,b,3,"loopEnd",c,d,e)}};l.prototype.x2time=function(a,b){a*=this.scale;var c=this.xs[b];var d=1;if(a<c[0])H({key:" "});else{for(;d<c.length&&c[d]<a;)d+=1;if(d==c.length)H({key:" "});else{var e=this.lbtix[b][d];if(!e[this.repcnt]){var k=Object.keys(e);this.repcnt=this.repcnt<k[0]?parseInt(k[0]):parseInt(k[k.length-1])}e=e[this.repcnt];k=this.times;var g=c[d-1];var l=c[d];c=k[e-1];k=c+(k[e]-c)*(a-g)/(l-g);opt.lopctl?this.doLoopTag(a,b,k,d,e):opt.synbox&&(t?h.getPlayerState()==YT.PlayerState.PLAYING:
!h.paused)?this.syncTimes(a,d,b,e):ja(!1,(opt.lncsr?k:c+.01)+q)}}};l.prototype.goMsre=function(a){var b=this.time_ix;h&&(a=a?this.times[b]+.01:2>=b?.01:this.times[b-2]+.01,ja(!1,a+q))};l.prototype.showSyncInfo=function(){var a=this.time_ix;a=this.times[a]-this.times[a-1];$("#sync_info").html("duration&nbsp;measure:<br>"+a.toFixed(3)+" sec.<br>");$("#sync_info").append("media&nbsp;offset:<br>"+q.toFixed(3)+" sec.")};l.prototype.changeTimesKeyb=function(a){this.changeTimes(this.lbtix[this.line][this.msre][this.repcnt]-
1,a,0)};l.prototype.changeTimes=function(a,b,c){var d=this.times;for(a+=1;a<d.length;++a){var e=c?d[a-1]+c:d[a]+b;d[a]=e}};l.prototype.syncTimes=function(a,b,c,d){a=this.lbtix[c][b][this.repcnt]-1;c=(t?h.getCurrentTime():h.currentTime)-q-.2;0==a?(q+=c,t?h.seekTo(q+.01,!0):h.currentTime=q+.01,Y&&$("#woff").click()):(--a,b=2==d?0:this.times[d-2],d=this.times[d-1],c<b+.5?alert("tempo faster than 240 bpm: first sync previous measures"):(this.lastSync>a?this.changeTimes(a,c-d,0):(this.changeTimes(a,0,
c-b),this.lastSync=a),opt.jump&&(t?h.seekTo(b+q+.01,!0):h.currentTime=b+q+.01)))};l.prototype.setSize=function(){var a;for(a=0;a<y.length;++a){var b=y[a];var c=b.width.baseVal.value;var d=b.height.baseVal.value;var e=$("#notation").prop("clientWidth");b.width.baseVal.value=e;b.height.baseVal.value=e*d/c}};l.prototype.setScale=function(){var a=y[0];var b=a.getBoundingClientRect().width;a=a.viewBox.baseVal.width;var c=P[0].get(0).transform.baseVal;c=c.numberOfItems?c.getItem(0).matrix.a:1;this.scale=
a/c/b;c=$("#notation").position();var d=$("#notation").scrollTop();this.line_offsets=[];for(b=0;b<y.length;++b)a=$(y[b]).position(),this.line_offsets[b]=d+a.top-c.top;this.line_offsets[b]=$("#notation")[0].scrollHeight-500};l.prototype.compCountIn=function(){var a={time:.25,num:4},b=1<this.time_ix?this.time_ix-1:this.time_ix,c=Math.min(this.times.length-1,b+3);if(c>b){var d=this.tixbts.slice(b,c).reduce(function(a,b){return a+b},0);a.time=(this.times[c]-this.times[b])/d/opt.speed;a.num=this.tixbts[b]}return a};
n.prototype.pause=function(){this.clearKlok();W()};n.prototype.play=function(){this.paused=!1;if(-1==this.klok){var a=this;this.setKlok(function(){a.currentTime+=a.step/1E3*opt.speed;W()},this.step)}};n.prototype.setKlok=function(a,b){-1!=this.klok&&clearInterval(this.klok);this.klok=a?setInterval(a,b):-1;this.paused=!1;k&&opt.nocsr&&(k.noCursor=1)};n.prototype.clearKlok=function(){-1!=this.klok&&clearInterval(this.klok);this.klok=-1;this.paused=!0;k&&(k.noCursor=0)};var x=0;$(document).ready(function(){v=
document.getElementById("notation");ma=CSS.supports("scroll-behavior","smooth");$("#drpuse").prop("checked",!1);Ba()||Ca(!0);$(window).resize(ka);$("body").keydown(H);$("#save").click(Aa);$("#speed").change(function(){D(2)});$("#lopctl").click(ua);var a='<a href="http://wim.vree.org/js/">abcweb</a> (version: '+VERSION+")</br>\u00a9Willem Vree";a+='<br>using:<br><a href="http://moinejf.free.fr/js/">abc2svg</a>, \u00a9Jef Moine';$("#help").prepend('<div style="position: absolute; right: 5px;">'+a+"</div>");
$("#helpm").click(function(){$("#help").toggleClass("showhlp")});$("#meddiv").on("mousedown touchstart",Ra);$("#rollijn").on("mousedown touchstart",Sa);$("#fknp").change(function(){qa("btn",[])});$("#mknp").change(function(){ea("btn",[])});$("#yknp").click(Ia);$("#yubid").keydown(function(a){a.stopPropagation()});$("#yubuse").change(ta);$("#drpuse").click(ya);$("#notation").mousedown(function(){Da()||H({key:" "})});$("#jump").change(Ea);$("#impbox").change(r);$("#menu * input").change(Ea);$("#menu label").toggle();
$("#mbar").click(function(){"none"==$("#menu label").css("display")?$("#menu label").toggle(!0):Fa()});$("#woff").change(function(){Y=$(this).prop("checked")});$.event.props.push("dataTransfer");$("body").on("drop",Ha);$("body").on("dragover",function(a){a.stopPropagation();a.preventDefault();a.dataTransfer.dropEffect="copy"});$("body").on("dragenter dragleave",function(){$(this).toggleClass("indrag")});$("#fscr").on("change",Ta);$("body").on("fullscreenchange webkitfullscreenchange mozfullscreenchange",
function(){var a=document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement;$("#fscr").prop("checked",null!=a)});$("body").on("play_end",function(){B>=play_list.length||(Ba(play_list[B]),B+=1)})})})();
