//~ Revision: 114, Copyright (C) 2016-2018: Willem Vree, contributions Stéphane David.
//~ This program is free software; you can redistribute it and/or modify it under the terms of the
//~ GNU General Public License as published by the Free Software Foundation; either version 2 of
//~ the License, or (at your option) any later version.
//~ This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//~ without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//~ See the GNU General Public License for more details. <http://www.gnu.org/licenses/gpl.html>.
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,h){a!=Array.prototype&&a!=Object.prototype&&(a[c]=h.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var c=0;c<a.length;++c){var h=a[c];if(h&&h.Math==Math)return h}return globalThis};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(a,c){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function a(h){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(h||"")+"_"+c++,h)}var c=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,c){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var h=0,n={next:function(){if(h<a.length){var e=h++;return{value:c(e,a[e]),done:!1}}n.next=function(){return{done:!0,value:void 0}};return n.next()}};n[Symbol.iterator]=function(){return n};return n};
$jscomp.polyfill=function(a,c,h,n){if(c){h=$jscomp.global;a=a.split(".");for(n=0;n<a.length-1;n++){var e=a[n];e in h||(h[e]={});h=h[e]}a=a[a.length-1];n=h[a];c=c(n);c!=n&&null!=c&&$jscomp.defineProperty(h,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");$jscomp.polyfill("Math.log10",function(a){return a?a:function(a){return Math.log(a)/Math.LN10}},"es6","es3");
$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function h(a){return a instanceof e?a:new e(function(r,c){r(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var r=this;this.asyncExecuteFunction(function(){r.executeBatch_()})}this.batch_.push(a)};var n=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(a){n(a,0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var B=0;B<a.length;++B){var c=a[B];a[B]=null;try{c()}catch(S){this.asyncThrow_(S)}}}this.batch_=null};c.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var r=this.createResolveAndReject_();try{a(r.resolve,r.reject)}catch(R){r.reject(R)}};e.prototype.createResolveAndReject_=function(){function a(a){return function(r){e||(e=!0,a.call(c,r))}}var c=this,e=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var r=null!=a;break a;case "function":r=!0;break a;default:r=!1}r?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var r=void 0;try{r=a.then}catch(R){this.reject_(R);return}"function"==typeof r?
this.settleSameAsThenable_(r,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,c){if(0!=this.state_)throw Error("Cannot settle("+a+", "+c+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=c;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)X.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var X=new c;e.prototype.settleSameAsPromise_=function(a){var c=this.createResolveAndReject_();a.callWhenSettled_(c.resolve,c.reject)};e.prototype.settleSameAsThenable_=function(a,c){var e=this.createResolveAndReject_();try{a.call(c,e.resolve,e.reject)}catch(S){e.reject(S)}};e.prototype.then=function(a,c){function r(a,c){return"function"==typeof a?function(c){try{h(a(c))}catch(Y){n(Y)}}:c}var h,n,B=new e(function(a,c){h=a;n=c});this.callWhenSettled_(r(a,h),r(c,n));return B};
e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,c){function e(){switch(h.state_){case 1:a(h.result_);break;case 2:c(h.result_);break;default:throw Error("Unexpected state: "+h.state_);}}var h=this;null==this.onSettledCallbacks_?X.asyncExecute(e):this.onSettledCallbacks_.push(e)};e.resolve=h;e.reject=function(a){return new e(function(c,e){e(a)})};e.race=function(a){return new e(function(c,e){for(var r=$jscomp.makeIterator(a),n=r.next();!n.done;n=r.next())h(n.value).callWhenSettled_(c,
e)})};e.all=function(a){var c=$jscomp.makeIterator(a),n=c.next();return n.done?h([]):new e(function(a,e){function r(c){return function(e){B[c]=e;C--;0==C&&a(B)}}var B=[],C=0;do B.push(void 0),C++,h(n.value).callWhenSettled_(r(B.length-1),e),n=c.next();while(!n.done)})};return e},"es6","es3");var xmlplay_VERSION=114;
(function(){function a(b){F.innerHTML+=b+"\n"}function c(b){a(b);v.innerHTML+=b+"<br>"}function h(b){a(b);v.innerHTML+='<div style="white-space: nowrap">'+b+"</div>"}function n(b){var k=b.slice(0,4E3);0<=k.indexOf("X:")?B(b):-1==k.indexOf("<?xml ")?alert("not an xml file nor an abc file"):(b=(new window.DOMParser).parseFromString(b,"text/xml"),k={p:"f",t:1,u:0,v:3,m:2,mnum:0},Ka&&(k.p=""),La&&(k.x=1),b=vertaal(b,k),b[1]&&a(b[1]),B(b[0]))}function e(){var b,a=new FileReader;a.onload=function(b){n(a.result)};
if(b=pa?pa[0]:aa.files[0])qa=b.name.split(".")[0],a.readAsText(b)}function X(b){F.innerHTML="";var k=b[0].link;qa=b[0].name.split(".")[0];v.style.display="block";a("link: "+k+"<br>");var f=new XMLHttpRequest;f.open("GET",k,!0);f.onload=function(){a("XHR ok");v.style.display="none";n(f.responseText)};f.onerror=function(){c("XHR failed")};f.send()}function r(b){b.stopPropagation();b.preventDefault();pa=b.dataTransfer.files;this.classList.remove("indrag");e()}function B(b){function a(a){var b,g,d,f,
k,l={},c={},e=[18,20,22,24,26,28];a=a.split("\n");for(b=0;b<a.length;++b){var h=a[b];if(0<=h.indexOf("strings")&&(g=h.match(/V:\s*(\S+).*strings\s*=\s*(\S+)/))){var n=g[1];l[n]={};g[2].split(",").forEach(function(a,b){d=a[0];f=12*parseInt(a[1]);k=f+[0,2,4,5,7,9,11]["CDEFGAB".indexOf(d)]+12;l[n][e[b]]=k});c[n]=0<=h.indexOf("diafret")}}return[l,c]}function f(a){var b,g,d={};a=a.split("\n");for(b=0;b<a.length;++b){var f=a[b];if(0<=f.indexOf("%%map")&&(g=f.match(/%%map *(\S+) *(\S+).*midi=(\d+)/))){f=
g[1];var k=g[2];g=g[3];d[f+k]=parseInt(g)}}return d}function d(a){var b={diamond:1,triangle:1,square:1,normal:1},g=l,d,f="default",k={"default":[]},c={"default":[]};a=a.split("\n");for(d=0;d<a.length;++d){var e=a[d];if(0<=e.indexOf("I:percmap")){e=e.split(" ").map(function(a){return a.trim()});var h=e[4];h in b&&(h=h+"+,"+h);e="%%map perc"+f+" "+e[1]+" print="+e[2]+" midi="+e[3]+" heads="+h;k[f].push(e)}0<=e.indexOf("%%MIDI")&&c[f].push(e);0<=e.indexOf("V:")&&(h=e.match(/V:\s*(\S+)/))&&(f=h[1],f in
k||(k[f]=[],c[f]=[]))}b=Object.keys(k).sort();for(d=0;d<b.length;++d)g=g.concat(k[b[d]]);f="default";for(d=0;d<a.length;++d)e=a[d],0<=e.indexOf("I:percmap")||0<=e.indexOf("%%MIDI")||(0<=e.indexOf("V:")||0<=e.indexOf("K:")?((h=e.match(/V:\s*(\S+)/))&&(f=h[1]),g.push(e),f in c&&c[f].length&&(g=g.concat(c[f]),delete c[f]),0<=e.indexOf("perc")&&-1==e.indexOf("map=")&&(e+=" map=perc"),0<=e.indexOf("map=perc")&&0<k[f].length&&g.push("%%voicemap perc"+f),0<=e.indexOf("map=off")&&g.push("%%voicemap")):g.push(e));
return g.join("\n")}var l='%%beginsvg\n<defs>,<text id="x" x="-3" y="0">&#xe263;</text>,<text id="x-" x="-3" y="0">&#xe263;</text>,<text id="x+" x="-3" y="0">&#xe263;</text>,<text id="normal" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal-" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal+" x="-3.7" y="0">&#xe0a4;</text>,<g id="circle-x"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<g id="circle-x-"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<path id="triangle" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle-" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle+" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="fill:#000"></path>,<path id="square" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square-" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square+" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="fill:#000"></path>,<path id="diamond" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond-" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond+" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="fill:#000"></path>,</defs>\n%%endsvg'.split(",");
0<=b.indexOf("I:percmap")&&(b=d(b));0<=b.indexOf("%%map")&&(Ma=f(b));0<=b.indexOf(" strings")&&a(b);ra=b;R(b);S(b)}function R(b){function k(a){var b=[];a.forEach(function(a,d){b[a.st]?b[a.st].push(d):b[a.st]=[d];a.clef.clef_octave&&(ba[d]=a.clef.clef_octave);Na[a.st]=6*(a.stafflines||"|||||").length*(a.staffscale||1);I[d]=a.midictl&&a.midictl[7];void 0==I[d]&&(I[d]=100);J[d]=a.midictl&&a.midictl[10];void 0==J[d]&&(J[d]=64);g[d]=a.instr?a.instr:0});return b}var f="",d=[3,0,4,1,5,2,6],l=[0,2,4,5,7,
9,11];N=[];ba=[];K.value=O=P=120;I=[];J=[];var g=[];var e=new Abc({img_out:null,errmsg:function(a,b,d){f+=a+"\n"},read_file:function(a){return""},anno_start:null,get_abcmodel:function(a,f,e){function c(a,b){p[a]=[0,0,0,0,0,0,0];H[a]={};h[a]=b;var f=0<=b;(f?d.slice(0,b):d.slice(b)).forEach(function(b){p[a][b]+=f?1:-1})}var p={},D={"-2":-2,"-1":-1,0:0,1:1,2:2,3:0},H={},h={},G={},n={ppp:30,pp:45,p:60,mp:75,mf:90,f:105,ff:120,fff:127},r=[];e=f[0].meter.a_meter;e.length&&parseInt(e[0].top);for(q=0;q<f.length;++q)c(q,
f[q].key.k_sf),G[q]={};e={};Oa=f.length;sa=k(f);for(var m=a;m;m=m.ts_next){var z=[],q;switch(m.type){case 14:a=m.tempo_notes.reduce(function(a,b){return a+b});P=m.tempo*a/384;0==m.time&&(K.value=O=P);break;case 10:var A={t:m.time,mnum:-1,dur:m.dur};z.push(A);N.push({t:m.time,ix:m.istart,v:m.v,ns:z,inv:m.invis,tmp:P});break;case 8:var y=g[m.v];"p"==m.p_v.clef.clef_type&&(y+=128);for(a=0;a<m.notes.length;++a){f=m.notes[a];var t=f.pit+19;q=m.v;m.a_dd&&m.a_dd.forEach(function(a){(x=n[a.name])&&sa[m.st].forEach(function(a){r[a]=
x})});var x=r[q]||60;ba[q]&&(t+=ba[q]);A=Math.floor(t/7);var u=t%7;void 0!=f.acc&&(H[q][t]=D[f.acc]);A=12*A+l[u]+(t in H[q]?H[q][t]:p[q][u]);u=m.p_v.map;f.midi&&(A=f.midi);if(128<=y&&"MIDIdrum"!=u){var v=b.substring(m.istart,m.iend);v=v.match(/[=_^]*[A-Ga-g]/)[0];(u=Ma[u+v])&&(A=u)}A=128*y+A;e[A]=1;A={t:m.time,mnum:A,dur:m.dur,velo:x};t in G[q]?(G[q][t].dur+=m.dur,f.tie_ty||delete G[q][t],A.mnum=-1):f.tie_ty&&(G[q][t]=A);z.push(A)}if(0==z.length)break;N.push({t:m.time,ix:m.istart,v:m.v,ns:z,stf:m.st,
tmp:P});break;case 5:c(m.v,m.k_sf);break;case 0:c(m.v,h[m.v]);N.push({t:m.time,ix:m.istart,v:m.v,bt:m.bar_type,tx:m.text});break;case 16:m.instr&&(g[m.v]=m.instr),7==m.ctrl&&(I[m.v]=m.val),10==m.ctrl&&(J[m.v]=m.val)}}ta.forEach(function(a){var b=a.parentNode;b&&b.removeChild(a)});ca=[];D="#f9f #3cf #c99 #f66 #fc0 #cc0 #ccc".split(" ");for(a=0;a<Oa;++a)G=1<<a&ua?"0":"",q=document.createElementNS("http://www.w3.org/2000/svg","rect"),q.setAttribute("fill",D[a%D.length]+G),q.setAttribute("fill-opacity",
"0.5"),q.setAttribute("width","0"),ta.push(q),ca.push(-1);va=Object.keys(e);null!=w?da():alert("Your browser has no Web Audio API -> no playback.")}});e.tosvg("play","%%play");e.tosvg("abc2svg",b);""==f&&(f="no error");a(f.trim())}function S(b){function k(a){a.stopPropagation();var b=a.clientX;b-=this.getBoundingClientRect().left;var d=b*ea;if(d<p+24||d>H)T();else{var f=L.indexOf(this);var g=(a.clientY-this.getBoundingClientRect().top)*ea;b=fa[f];for(a=0;a<b.length;a++)if(b[a]>g){ha=a;Z(f);break}for(a=
0;a<y.length;++a)if(g=y[a].xy)if(b=y[a].vce,-1!=sa[ha].indexOf(b)){var k=g[0];b=g[1];g=g[3];if(!(k<f)&&d<parseFloat(b)+g){t=a;for(d=y[a].t;y[a]&&y[a].t==d;)C(y[a]),a+=1;break}}}}var f="",d="",l=0;t=0;wa={};fa=[];var g={},e,c,p=1E3,H=0;ha=0;if(b){var h=new Abc({imagesize:'width="100%"',img_out:function(a){-1!=a.indexOf("<svg")&&(fa[l]=Object.keys(g),g={},l+=1,e<p&&(p=e),c>H&&(H=c));f+=a},errmsg:function(a,b,f){d+=a+"\n"},read_file:function(a){return""},anno_start:function(a,b,d,f,k,p,D){if("note"==
a||"rest"==a)f=h.ax(f).toFixed(2),k=h.ay(k).toFixed(2),D=h.ah(D),wa[b]=[l,f,k,p,D];"bar"==a&&(k=h.ay(k),D=h.ah(D),k=Math.round(k+D),g[k]=1,c=h.ax(f),e=h.ax(0))},get_abcmodel:null});h.tosvg("abc2svg",b);""==d&&(d="no error");a(d.trim());f&&(u.innerHTML='<div id="leeg" style="height:'+xa+'px">&nbsp;</div>',u.innerHTML+=f,u.innerHTML+='<div id="leeg" style="height:'+xa+'px">&nbsp;</div>',ia(document.getElementById("leeg"),"click",T),L=Array.prototype.slice.call(u.getElementsByTagName("svg")),b=Array.prototype.slice.call(u.getElementsByClassName("g")),
ya=b.length?b:L,Ia(),L.forEach(function(a){db&&(a.style.display="none");ia(a,"click",k)}),cb())}}function Ia(){if(0!=L.length){var a=L[0];var k=a.getBoundingClientRect().width;try{var f=a.viewBox.baseVal.width}catch(l){f=k}var d=(d=ya[0].transform)?d.baseVal:[];d=d.numberOfItems?d.getItem(0).matrix.a:1;ea=f/d/k}}function Z(a){var b=void 0!=a;void 0==a&&(a=Pa);var f=Q.getBoundingClientRect().top,d=L[a].getBoundingClientRect().top,l=ha;f=Math.round(u.scrollTop+d+(fa[a][l]-Na[l])/ea-30-f);f!=u.scrollTop&&
(U&&(u.style["scroll-behavior"]=b?"smooth":"auto"),u.scrollTop=f);Pa=a}function Ja(a){function b(a){u.getBoundingClientRect();l.style.top=(d?a.touches[0].clientY:a.clientY)-15+"px";Z()}function f(a){l.removeEventListener("mousemove",b);l.removeEventListener("touchmove",b);l.removeEventListener("mouseup",f);l.removeEventListener("touchend",f);l.removeEventListener("mouseleave",f);l.style.cursor="";l.classList.remove("spel")}a.preventDefault();var d="touchstart"==a.type,l=Q;l.style.cursor="row-resize";
l.classList.add("spel");l.addEventListener("mousemove",b);l.addEventListener("touchmove",b);l.addEventListener("mouseup",f);l.addEventListener("touchend",f);l.addEventListener("mouseleave",f)}function C(a){var b,f;var d=ta[a.vce];if(b=a.xy){var l=b[0];var g=b[1];var e=b[2];var c=b[3];b=b[4];a.inv&&(b=c=0);l!=ca[a.vce]&&((f=d.parentNode)&&f.removeChild(d),f=ya[l],f.insertBefore(d,f.firstChild),ca[a.vce]=l,Z(l));d.setAttribute("x",g);d.setAttribute("y",e);d.setAttribute("width",c);d.setAttribute("height",
b)}else d.setAttribute("width",0),d.setAttribute("height",0)}function cb(){var a=0<t?y[t].t:0;y=[];za={};var k=1,f=0,d=0,l=0,g=0,e=0,c;for(c=0;c<N.length;++c){var p=N[c];if(p.bt&&0==p.v){if(p.t in za&&":"==p.bt[0])continue;if(1==k&&":"==p.bt[0]&&p.t>l){c=d-1;k=2;f+=p.t-l;continue}2==k&&":"==p.bt[0]&&p.t>l&&(k=1);1==k&&":"==p.bt[p.bt.length-1]&&(d=c,l=p.t);g&&(p.tx||"|"!=p.bt)&&(g=0,f-=p.t-e);2==k&&"1"==p.tx&&(g=1,e=p.t)}g||(p.bt?za[p.t]=1:y.push({t:p.t+f,xy:wa[p.ix],ns:p.ns,vce:p.v,inv:p.inv,tmp:p.tmp}))}for(t=
0;t<y.length&&(p=y[t],!(p.t>=a)||p.inv);++t);t==y.length&&--t;C(y[t])}function Y(){if(w){for(var a=1E3*w.currentTime,k=0,f;0==k;){var d=y[t];d.tmp!=O&&(O=d.tmp,K.value=Math.round(O*Aa));f=156.25/(d.tmp*Aa);t==y.length-1?(t=-1,k=d.ns[0].dur+1E3):(k=y[t+1].t,k=(k-d.t)*f);d.ns.forEach(function(b,g){f=192>=b.dur?1.3*f:1.1*f;g=b.mnum;var k=b.dur*f,e=d.vce;b=b.velo;if(-1!=g){var c=g>>7;if(c in Ba&&E){var l=g%128;g=a/1E3;k=(k-1)/1E3;var h=Ca[c][l];if(h){var n=w.createBufferSource(),t=h.useflt,r=h.uselfo,
u=h.useenv,y=I[e]/127;e=(J[e]-64)/64;n.buffer=h.buffer;h.loopStart&&(n.loop=!0,n.loopStart=h.loopStart,n.loopEnd=h.loopEnd);n.playbackRate.value=Da[c][l];if(r){var x=w.createOscillator();x.frequency.value=h.lfofreq;c=w.createGain();c.gain.value=h.lfo2vol;x.connect(c);var v=w.createGain();v.gain.value=1;c.connect(v.gain);c=w.createGain();c.gain.value=h.lfo2ptc;x.connect(c);c.connect(n.detune)}if(t){var m=w.createBiquadFilter();m.type="lowpass";m.frequency.value=h.filter}if(u){var z=1;c=w.createGain();
c.gain.setValueAtTime(0,g);c.gain.linearRampToValueAtTime(z,g+h.envatt);l=h.envhld;var q=h.envdec;if(k>l){c.gain.setValueAtTime(z,g+l);if(k<q){var A=k-l;q=A/(q-l)*h.envsus}else A=q-l,q=h.envsus;z*=q;c.gain.linearRampToValueAtTime(z,g+l+A)}c.gain.setValueAtTime(z,g+k);l=g+k+z*h.envrel;c.gain.linearRampToValueAtTime(0,l);var B=w.createConstantSource();B.offset.value=h.env2flt;B.connect(c);c.connect(m.detune)}if(V){var C=w.createStereoPanner();C.pan.value=e}z=b*y*h.atten*eb;0==z&&(z=1E-5);b=w.createGain();
b.gain.setValueAtTime(1E-5,g);b.gain.exponentialRampToValueAtTime(z,g+h.attack);l=h.hold;q=h.decay;k>l&&(b.gain.setValueAtTime(z,g+l),k<q?(A=k-l,q=Math.pow(10,A/(q-l)*Math.log10(h.sustain))):(A=q-l,q=h.sustain),z*=q,b.gain.exponentialRampToValueAtTime(z,g+l+A));b.gain.setValueAtTime(z,g+k);l=g+k+(100+20*Math.log10(z))/100*h.release;b.gain.exponentialRampToValueAtTime(1E-5,l);t?(n.connect(m),m.connect(C||b)):n.connect(C||b);C&&C.connect(b);r?(b.connect(v),v.connect(w.destination)):b.connect(w.destination);
n.start(g);r&&x.start(g+h.lfodel);u&&B.start(g);n.stop(l);r&&x.stop(l);u&&B.stop(l)}}else c in ja&&(v=[144,g,b],Qa(v,a,e),v[2]=0,Qa(v,a+k-1,e))}});C(d);t+=1}clearTimeout(Ea);Ea=setTimeout(Y,k)}else alert("Your browser has no Web Audio API -> no playback.")}function fb(a){switch(a.key){case "ArrowLeft":case "Left":--t;C(y[t]);break;case "ArrowRight":case "Right":t+=1;C(y[t]);break;case "ArrowUp":case "Up":Fa(1);break;case "ArrowDown":case "Down":Fa(-1);break;case "m":$("#mbar").click();break;case "t":v.style.display=
"none"==v.style.display?"block":"none";break;case " ":a.preventDefault&&a.preventDefault(),T()}}function T(){y.length&&((Ra=1-Ra)?(ka.value="Stop",la.style.display="none",Y()):(ka.value="Play",clearTimeout(Ea)))}function Fa(a){var b=K.value-0;"number"==typeof a&&(K.value=b+a);Aa=b/O}function Qa(a,c,f){if(0!=Sa){var b=a[0]&240,k=a[2];a=a[1];c/=1E3;128==b&&Ta(a,c);if(144==b)if(0<k){b=I[f]/127;f=(J[f]-64)/64;var g=w.createBufferSource();g.buffer=Ua[a];var e=w.createGain();e.gain.setValueAtTime(1E-5,
c);k=k*b*.015625;0==k&&(k=1E-5);e.gain.exponentialRampToValueAtTime(k,c+.001);if(V){var h=w.createStereoPanner();h.pan.value=f}g.connect(h||e);h&&h.connect(e);e.connect(w.destination);g.start(c);Ga[a]=[g,e,k]}else Ta(a,c)}}function Ta(a,c){var b=Ga[a],d=b[0],e=b[1];b=b[2];d&&(e.gain.setValueAtTime(b,c),e.gain.exponentialRampToValueAtTime(1E-5,c+.1),d.stop(c+.1),Ga[a]=void 0)}function Va(a){return new Promise(function(b,f){for(var d=atob(a),c=new ArrayBuffer(d.length),g=new Uint8Array(c),e=0;e<d.length;e++)g[e]=
d.charCodeAt(e);w.decodeAudioData(c,function(a){b(a)},function(a){f("error dedoding audio sample")})})}function gb(a){return new Promise(function(b,f){function d(c){var g=instData[c];if(!g&&c<instData.length-1)d(c+1);else{var e={attack:g.attack,hold:g.hold,decay:g.decay,sustain:g.sustain,release:g.release,atten:g.atten,filter:g.filter,lfodel:g.lfodel,lfofreq:g.lfofreq,lfo2ptc:g.lfo2ptc,lfo2vol:g.lfo2vol,envatt:g.envatt,envhld:g.envhld,envdec:g.envdec,envsus:g.envsus,envrel:g.envrel,env2flt:g.env2flt,
uselfo:ma&&.008<g.lfofreq&&(0!=g.lfo2ptc||0!=g.lfo2vol),useflt:na&&16E3>g.filter,useenv:oa&&16E3>g.filter&&0!=g.env2flt};g.loopStart&&(e.loopStart=g.loopStart,e.loopEnd=g.loopEnd);var k=g.scale;var h=g.tune;for(var l=g.keyRangeLo;l<=g.keyRangeHi;l++)Da[a][l]=Math.pow(Math.pow(2,1/12),(l+h)*k),Ca[a][l]=e;Va(g.sample).then(function(a){e.buffer=a;c<instData.length-1?d(c+1):(instData="",b("ok"))}).catch(function(a){f(a)})}}Da[a]=[];Ca[a]=[];d(0)})}function Wa(a,c){return new Promise(function(b,d){var f=
document.createElement("script");f.src=c;f.onload=function(){b("ok");document.head.removeChild(f)};f.onerror=function(b){d("could not load instrument "+a)};document.head.appendChild(f)})}function da(){function b(a,f,d,e){var g=f[a];a==f.length?e():g in Ba?b(a+1,f,x.sf2url1,e):(h(a+" loading instrument: "+g+(d?" from: "+d:"")),Wa(g,d+"instr"+g+"mp3.js").then(function(){return gb(g)}).then(function(){Ba[g]=1;b(a+1,f,x.sf2url1,e)}).catch(function(g){c(g);d==x.sf2url1&&x.sf2url2?b(a,f,x.sf2url2,e):(c(" ... switch to MIDI-js"),
E=0,da())}))}function e(a,b,f,d){var g=b[a],k=g in x.instTab?x.instTab[g]:hb[g];if(a==b.length)d();else if(ja[g])e(a+1,b,x.midijsUrl1,d);else{var l=f+k+"-mp3.js";h(a+" loading instrument: "+g+" from: "+l+"...");Wa(g,l).then(function(){ja[g]=MIDI.Soundfont[k];e(a+1,b,x.midijsUrl1,d)}).catch(function(g){c(g);f==x.midijsUrl1?e(a,b,x.midijsUrl2,d):c(" ... give up")})}}function f(b,d){if(b==d.length)Sa=1,v.style.display="none",a("notes decoded");else{var g=d[b],c=g>>7,e=g%128,k=ja[c]["C Db D Eb E F Gb G Ab A Bb B".split(" ")[e%
12]+(Math.floor(e/12)-1)].split(",")[1];Va(k).then(function(a){Ua[g]=a;v.innerHTML+=", "+c+":"+e;Xa[g]=1;f(b+1,d)})}}var d={};va.forEach(function(a){d[a>>7]=1});v.innerHTML=E?"Loading SF2 fonts<br>":"Loading MIDI-js fonts<br>";v.style.display="block";if(E)document.getElementById("sf2").checked="true",b(0,Object.keys(d),x.sf2url1,function(){v.style.display="none";a("fonts geladen")});else{document.getElementById("midijs").checked="true";var l=va.filter(function(a){return!(a in Xa)});e(0,Object.keys(d),
x.midijsUrl1,function(){a("fonts geladen");v.innerHTML+="decode notes:";f(0,l)})}}function ib(){var b="",c="",f,d={},e;F.innerHTML="";var g=window.location.href.replace("?dl=0","").split("?");if(1<g.length)for(g=g[1].split("&"),f=0;f<g.length;f++)if(d=g[f].replace(/d:(\w{15}\/[^.]+\.)/,"https://dl.dropboxusercontent.com/s/$1"),"noErr"==d)var h=1;else if("noMenu"==d)var r=1;else if("noSave"==d)var p=1;else if("noErr"==d)h=1;else if("noDash"==d)var t=1;else"noRT"==d?E=0:"noPF"==d?Ka=1:"noLB"==d?La=
1:(e=d.match(/noCur=([\da-fA-F]{2})/))?ua=parseInt(e[1],16):"nosm"==d?U=!1:"ios"==d?U=V=oa=na=ma=0:(e=d.match(/sf2=(\w+)/))?x.sf2url2=e[1]+"/":c=d;if(g=document.getElementById("parms"))g.style.display="none";d=g?JSON.parse(g.innerHTML):{};void 0!=d.topSpace&&(xa=d.topSpace);void 0!=d.notationHeight&&(Ya=d.notationHeight);void 0!=d.fileURL&&(c=d.fileURL);void 0!=d.gTempo&&(P=d.gTempo);void 0!=d.noCur&&(ua=d.noCur);if(void 0!=d.noDash&&d.noDash||t)Q.style.visibility="hidden";if(void 0!=d.noSave&&d.noSave||
p)document.getElementById("savlbl").style.display="none";if(void 0!=d.noMenu&&d.noMenu||r)document.getElementById("mbar").style.display="none";if(void 0!=d.noErr&&d.noErr||h)F.style.display="none",F.style.height="0px";void 0!=d.instTab&&(x.instTab=d.instTab);void 0!=d.sf2url1&&(x.sf2url1=d.sf2url1);void 0!=d.sf2url2&&(x.sf2url2=d.sf2url2);void 0!=d.midijsUrl1&&(x.midijsUrl1=d.midijsUrl1);void 0!=d.midijsUrl2&&(x.midijsUrl2=d.midijsUrl2);/(\.xml$)|(\.abc$)/.test(c)&&(b=c,c="");if(b){var v=document.getElementById("wait");
v.style.display="block";var u=new XMLHttpRequest;u.open("GET",b,!0);u.onload=function(){a("preload ok");n(u.response);la.style.display="block";v.style.display="none"};u.onerror=function(){v.innerHTML+="\npreload failed"};u.send()}}function Za(){var a=F.clientHeight;a=Math.round(100*a/document.documentElement.clientHeight);u.style.height=Ya-a+"%"}function jb(){var b="",c="";if(ra&&((new Abc({imagesize:'width="100%"',img_out:function(a){b+=a},errmsg:function(a,b,d){c+=a+"\n"},read_file:null,anno_start:null,
get_abcmodel:null})).tosvg("abc2svg",ra),""==c&&(c="no error"),a(c.trim()),b)){var f='<html><meta charset="utf-8"><div>\n'+b+"\n</div></html>\n";var d=qa+".html";try{var e=document.createElement("a");e.href="data:text/plain;charset=utf-8,"+encodeURIComponent(f);e.download=d;e.text="Save ABC file";document.getElementById("saveDiv").appendChild(e);e.click()}catch(g){confirm("Do you want to save the ABC text?")&&(document.open("text/html"),document.write("<pre>"+f+"</pre>"),document.close())}}}function ia(a,
c,f){function b(f){a.removeEventListener("mousedown",b);a.removeEventListener("touchend",b);console.log("event listeners removed from "+a.nodeName+"#"+a.id);w&&"suspended"==w.state&&w.resume().then(function(){console.log("resuming audioContext")})}a.addEventListener("mousedown",b);a.addEventListener("touchend",b);a.addEventListener(c,f)}function $a(){function b(a){M.checked=!a;M.disabled=a;ab.style.color=a?"#aaa":"#000"}if("undefined"==typeof Dropbox){b(!0);var c=document.createElement("script");
c.src="https://www.dropbox.com/static/api/2/dropins.js";c.onload=function(){b(!1);Dropbox.init({appKey:"ckknarypgq10318"});var a=Dropbox.createChooseButton({success:X,cancel:function(){},linkType:"direct",multiselect:!1,extensions:[".xml",".abc"]});bb.append(a);$a()};c.onerror=function(){a("loading dropbox API failed")};document.head.appendChild(c)}else document.querySelector(".dropbox-dropin-btn").style.display=M.checked?"inline-block":"none",aa.style.display=M.checked?"none":"inline-block"}function kb(){var a=
document.body,c=a.requestFullscreen||a.mozRequestFullScreen||a.webkitRequestFullscreen,f=document.exitFullscreen||document.mozCancelFullScreen||document.webkitExitFullscreen;c&&f&&($("#fscr").prop("checked")?c.call(a):f.call(document))}var x={sf2url1:"./",sf2url2:"",instTab:{},midijsUrl1:"./",midijsUrl2:"https://rawgit.com/gleitz/midi-js-soundfonts/gh-pages/FluidR3_GM/"},ra,N,sa,Oa,qa,t=0,Ra=0,Ea,Sa=0,U,y=[],ba=[],za={},wa={},fa=[],L=[],ya=[],db,xa=500,ea,ha=0,ca=[],Pa=0,ta=[],w=null,Ua=[],Ga=[],
Xa={},va=[],Ya=100,pa=null,Na=[],Ba={},ja=[],Ma={},I=[],J=[],u=null,v,F,bb,Q,aa,K,M,ab,Ha,W,la,ka,hb="acoustic_grand_piano bright_acoustic_piano electric_grand_piano honkytonk_piano electric_piano_1 electric_piano_2 harpsichord clavinet celesta glockenspiel music_box vibraphone marimba xylophone tubular_bells dulcimer drawbar_organ percussive_organ rock_organ church_organ reed_organ accordion harmonica tango_accordion acoustic_guitar_nylon acoustic_guitar_steel electric_guitar_jazz electric_guitar_clean electric_guitar_muted overdriven_guitar distortion_guitar guitar_harmonics acoustic_bass electric_bass_finger electric_bass_pick fretless_bass slap_bass_1 slap_bass_2 synth_bass_1 synth_bass_2 violin viola cello contrabass tremolo_strings pizzicato_strings orchestral_harp timpani string_ensemble_1 string_ensemble_2 synth_strings_1 synth_strings_2 choir_aahs voice_oohs synth_choir orchestra_hit trumpet trombone tuba muted_trumpet french_horn brass_section synth_brass_1 synth_brass_2 soprano_sax alto_sax tenor_sax baritone_sax oboe english_horn bassoon clarinet piccolo flute recorder pan_flute blown_bottle shakuhachi whistle ocarina lead_1_square lead_2_sawtooth lead_3_calliope lead_4_chiff lead_5_charang lead_6_voice lead_7_fifths lead_8_bass__lead pad_1_new_age pad_2_warm pad_3_polysynth pad_4_choir pad_5_bowed pad_6_metallic pad_7_halo pad_8_sweep fx_1_rain fx_2_soundtrack fx_3_crystal fx_4_atmosphere fx_5_brightness fx_6_goblins fx_7_echoes fx_8_scifi sitar banjo shamisen koto kalimba bagpipe fiddle shanai tinkle_bell agogo steel_drums woodblock taiko_drum melodic_tom synth_drum reverse_cymbal guitar_fret_noise breath_noise seashore bird_tweet telephone_ring helicopter applause gunshot".split(" "),
P=120,O=120,Aa=1,Ca=[],Da=[],E=1,Ka=0,La=0,ua=0,eb=.5/60,V=1,ma=1,na=1,oa=1;document.addEventListener("DOMContentLoaded",function(){v=document.getElementById("comp");u=document.getElementById("notation");F=document.getElementById("err");Q=document.getElementById("rollijn");bb=document.getElementById("abcfile");aa=document.getElementById("fknp");K=document.getElementById("tempo");la=document.getElementById("playbk");ka=document.getElementById("play");document.getElementById("kwart").appendChild(document.getElementById("mtrsvg"));
ia(ka,"click",T);ia(la,"click",T);aa.addEventListener("change",e);document.getElementById("save").addEventListener("click",jb);Q.addEventListener("mousedown",Ja);Q.addEventListener("touchstart",Ja);K.addEventListener("change",Fa);window.addEventListener("resize",function(){Ia();Za();Z()});u.addEventListener("drop",r);u.addEventListener("dragover",function(a){a.stopPropagation();a.preventDefault();a.dataTransfer.dropEffect="copy"});u.addEventListener("dragenter",function(){this.classList.add("indrag")});
u.addEventListener("dragleave",function(){this.classList.remove("indrag")});M=document.getElementById("drpuse");M.checked=!1;M.addEventListener("click",$a);ab=document.getElementById("drplbl");Ha=document.getElementById("mbar");W=document.getElementById("menu");W.style.display="none";Ha.addEventListener("click",function(a){a.stopPropagation();a="none"==W.style.display;W.style.display=a?"block":"none";Ha.style.background=a?"#aaa":""});W.addEventListener("click",function(a){a.stopPropagation()});U=
CSS.supports("scroll-behavior","smooth");ib();Za();var a=window.AudioContext||window.webkitAudioContext;w=void 0!=a?new a:null;a=["Your browser does not support:"];var c=0;U||a.push("* smooth scrolling");w?(w.createStereoPanner||(V=0),w.createOscillator||(ma=0),w.createBiquadFilter||(na=0),w.createConstantSource||(oa=0),V||a.push("* the StereoPanner element"),E&&!ma&&(a.push("* the Oscillator element"),c=1),E&&!na&&(a.push("* the BiquadFilter element"),c=1),E&&!oa&&(a.push("* the ConstantSource element"),
c=1),c&&(a.push("You are probably on iOS, which does not support the Web Audio API."),a.push("Real time synthesis is switched off, falling back to MIDIjs"),E=0,document.getElementById("midijs").checked="true")):a.push("* the Web Audio API -> no sound");1<a.length&&alert(a.join("\n"));document.getElementById("verlab").innerHTML="<span>Version:</span>"+xmlplay_VERSION;$("#fscr").on("change",kb);$("body").on("fullscreenchange webkitfullscreenchange mozfullscreenchange",function(){var a=document.fullscreenElement||
document.webkitFullscreenElement||document.mozFullScreenElement;$("#fscr").prop("checked",null!=a)});document.body.addEventListener("keydown",fb);document.getElementById("midijs").addEventListener("click",function(a){E=0;da()});document.getElementById("sf2").addEventListener("click",function(a){E=1;da()})})})();
